# Per-listener ACL auth
per_listener_settings true

# TLS listener — servicios internos
listener 8883 0.0.0.0
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf
allow_anonymous false

# Non-TLS listener — placas embebidas
listener 1884 0.0.0.0
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf
allow_anonymous false

# Healthcheck listener — localhost only (no auth)
listener 1883 127.0.0.1
allow_anonymous true

# Persistence
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
